experiment_duration: 5000000
step_duration: 1
preserve_population: true
experiment: "ADT"

selection:
  data: "./samples/ADT_2048.csv"
  d_fitness: 4
  t_size: 6
  fitness_sharing: true
  trace: true
  lexical: false
  fitness_weights:
    dirichlet: 0
    ingenuity: 300
    information: 20
    parsimony: 10


genotype:
  max_depth: 8
  min_len: 4
  max_len: 1200
  registers_n: 16
  max_steps: 1200
  mutation_rate: 0.1
  weight_crossover_points: true
  ops: "mov xor | & ~"

population:
  size: [16, 16]
  toroidal: true
  locality: 16
  n_elites: 10
  migration_rate: 0.5
  migration_type: "elite"

logging:
  log_every: 1
  save_every: 50

dashboard:
  server: "0.0.0.0"
  port: 9124
  enable: true
