experiment_duration: 50000
step_duration: 2
preserve_population: true
experiment: "2MUX-without-sharing-weighted"

selection:

  data: "./samples/2-MUX_overs-cohos-orbed_ALL.csv"
  d_fitness: 3
  t_size: 6
  fitness_sharing: false
  trace: true
  lexical: true

genotype:
  max_depth: 8
  min_len: 4
  max_len: 100
  data_n: 6
  registers_n: 4
  output_reg: 1
  max_steps: 512
  mutation_rate: 0.1
  weight_crossover_points: true
  ops: "& | mov ~"

population:
  size: [10, 10]
  toroidal: true
  locality: 16
  n_elites: 10
  migration_rate: 0.2
  migration_type: "elite"

logging:
  log_every: 1
  save_every: 50

dashboard:
  server: "0.0.0.0"
  port: 9124
  enable: true
